import request from 'supertest';
import { createServer } from '../server'; // assuming server.ts exports an express app
import { metrics } from '../src/utils/metrics';

/**
 * Simple end‑to‑end test harness that:
 *   1. Starts the Express server (in‑process).
 *   2. Loads a manifest of test scenarios (generated by generate_dataset.ts).
 *   3. Calls each API endpoint in the multimodal pipeline.
 *   4. Records predictions vs. ground‑truth and writes a JSON log.
 */

describe('THUNAI multimodal pipeline', () => {
  let app: any;
  beforeAll(() => {
    jest.setTimeout(25000);
    app = createServer();
  });

  const manifestPath = __dirname + '/fixtures/manifest.json';
  // Load manifest; if missing, the test will be skipped.
  let manifest: any[] = [];
  try {
    manifest = require(manifestPath);
  } catch {
    console.warn('Manifest not found – generate_dataset.ts must be run first.');
  }

  test.each(manifest)('scenario %s', async (scenario) => {
    // 1. Vision detection
    metrics.start('vision');
    const visionRes = await request(app)
      .post('/api/vision/detect')
      .send({ image_base64: scenario.image_base64 })
      .expect(200);
    metrics.end('vision', { objectsDetected: visionRes.body.objects.length });

    // 2. Speech transcription (if audio provided)
    let speechResult = null;
    if (scenario.audio_base64) {
      metrics.start('speech');
      const speechRes = await request(app)
        .post('/api/speech/transcribe')
        .send({ audio_base64: scenario.audio_base64, language: scenario.language })
        .expect(200);
      metrics.end('speech');
      speechResult = speechRes.body;
    }

    // 3. OCR extraction (if image with text)
    if (scenario.ocr_image_base64) {
      metrics.start('ocr');
      const ocrRes = await request(app)
        .post('/api/ocr/extract')
        .send({ image_base64: scenario.ocr_image_base64 })
        .expect(200);
      metrics.end('ocr');
    }

    // 4. Full multimodal processing (using internal helper)
    metrics.start('fullPipeline');
    const fullRes = await request(app)
      .post('/api/assistant/process')
      .send({
        image_base64: scenario.image_base64,
        audio_base64: scenario.audio_base64,
        text_input: scenario.text_input,
        profile_id: scenario.profile_id,
      })
      .expect(200);
    metrics.end('fullPipeline');

    // 5. Compare against ground‑truth
    // The manifest contains groundTruth fields for intent, risk, assistance, etc.
    const { intent_gt, risk_gt, assistance_gt } = scenario;
    const { intent_pred, risk_pred, assistance_pred } = fullRes.body;

    // Append a record to a temporary log file (metrics already writes a JSONL, we add a custom entry)
    const logEntry = {
      scenarioId: scenario.id,
      intent: { gt: intent_gt, pred: intent_pred },
      risk: { gt: risk_gt, pred: risk_pred },
      assistance: { gt: assistance_gt, pred: assistance_pred },
    };
    const fs = require('fs');
    const path = require('path');
    const logDir = path.resolve(__dirname, '../logs');
    if (!fs.existsSync(logDir)) fs.mkdirSync(logDir, { recursive: true });
    const logPath = path.join(logDir, 'pipeline_results.jsonl');
    fs.appendFileSync(logPath, JSON.stringify(logEntry) + '\n');
  }, 20000);

  test('validates the 5 Core Scientific Research Metrics via /api/benchmark/scientific-metrics', async () => {
    const res = await request(app)
      .get('/api/benchmark/scientific-metrics')
      .expect(200);

    const data = res.body;

    // 1. Distance MAE (m): Accuracy of spatial awareness
    expect(data.distance_mae_m).toBeDefined();
    expect(data.distance_mae_m).toBeGreaterThan(0);
    expect(data.distance_mae_m).toBeLessThanOrEqual(0.25); // Target < 0.25m

    // 2. Direction Accuracy (%): Correct front/left/right identification
    expect(data.direction_accuracy_pct).toBeDefined();
    expect(data.direction_accuracy_pct).toBeGreaterThanOrEqual(90.0); // Target > 90%
    expect(data.direction_accuracy_pct).toBeLessThanOrEqual(100.0);

    // 3. Gesture F1-Score (%): Reliability of gesture control
    expect(data.gesture_f1_score_pct).toBeDefined();
    expect(data.gesture_f1_score_pct).toBeGreaterThanOrEqual(88.0); // Target > 88%
    expect(data.gesture_f1_score_pct).toBeLessThanOrEqual(100.0);

    // 4. False Emergency Activation Rate (%): Safety and reliability
    expect(data.false_emergency_rate_pct).toBeDefined();
    expect(data.false_emergency_rate_pct).toBeGreaterThanOrEqual(0);
    expect(data.false_emergency_rate_pct).toBeLessThanOrEqual(3.0); // Target < 3%

    // 5. End-to-End Latency (ms): Real-time responsiveness
    expect(data.end_to_end_latency_ms).toBeDefined();
    expect(data.end_to_end_latency_ms).toBeGreaterThan(0);
    expect(data.end_to_end_latency_ms).toBeLessThanOrEqual(250); // Target < 200-250ms

    // Check table format
    expect(data.metrics_table).toHaveLength(5);
    expect(data.metrics_table[0].whatItProves).toBe('Accuracy of spatial awareness');
    expect(data.metrics_table[1].whatItProves).toBe('Correct front/left/right identification');
    expect(data.metrics_table[2].whatItProves).toBe('Reliability of gesture control');
    expect(data.metrics_table[3].whatItProves).toBe('Safety and reliability');
    expect(data.metrics_table[4].whatItProves).toBe('Real-time responsiveness');
  });
});
